[features]
seeds = false
skip-lint = false
[programs.localnet]
pulse_eor = "DafQCS2iwRB48xvjYa1Nsxz5wFDuMXq37qCmy4Sov8ce"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ruixiantay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
